name: diagnostics-monitor
run-name: Diagnostics Monitor Attempt
on: [push]
jobs:
  track-diagnostics:
    runs-on: ubuntu-latest
    steps:
      - name: Check out self
        uses: actions/checkout@v4
      - name: Check out private action
        uses: actions/checkout@v4
        with:
          repository: toBeOfUse/test-action
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/test-action
      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm install --ci
      - run: npx playwright install --with-deps
      - name: Finally do stuff
        uses: ./.github/actions/test-action
        with:
          issue-bot-app-id: ${{ secrets.BOT_APP_ID }}
          issue-bot-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          supabase-url: ${{ secrets.SUPABASE_URL }}
          supabase-key: ${{ secrets.SUPABASE_KEY }}
