name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  track-diagnostics:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: toBeOfUse/test-action
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/test-action
      - name: Run my action
        uses: ./.github/actions/test-action
